In [1]:
import csv
import tqdm
import numpy as np
import pandas as pd
import zipfile

# with zipfile.ZipFile("parsed_data_no_extra_season_3.zip", 'r') as zip_ref:
#     zip_ref.extractall("datasets")

In [2]:
df = pd.read_csv("parsed_test_data_no_extra_season_3.csv.zip", sep=',', compression='zip')
df.head()

Unnamed: 0.1  Unnamed: 0  ... ad_slot_screen_share  is_mobile_device
0             0           0  ...             0.026766             False
1             1           1  ...             0.071491             False
2             2           2  ...             0.038128             False
3             3           3  ...             0.071491             False
4             4           4  ...             0.062454             False

[5 rows x 19 columns]

In [3]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'bid_id', 'region_id', 'city_id',
       'domain', 'ad_slot_visibility', 'ad_slot_format', 'creative_id',
       'advertiser_id', 'user_profile_ids', 'click', 'part_of_day', 'weekday',
       'weekend', 'os', 'browser', 'ad_slot_screen_share', 'is_mobile_device'],
      dtype='object')

In [4]:
df = df.drop("Unnamed: 0", axis=1).drop("Unnamed: 0.1", axis=1)
df.head()

bid_id  ...  is_mobile_device
0  b8c557a16cdd9cea7fa61df79bdb392d  ...             False
1  ce5a2b810ada0cad122508b4a9d1e2fd  ...             False
2  61fb95442aaa7cade3761b7f329a1e73  ...             False
3  7f9c3a72df3e4ded04870c08fcbcf72b  ...             False
4  de8192350f7e0f3223c43cf0c8cfb247  ...             False

[5 rows x 17 columns]

In [5]:
df.dtypes

bid_id                   object
region_id                 int64
city_id                   int64
domain                   object
ad_slot_visibility       object
ad_slot_format           object
creative_id               int64
advertiser_id             int64
user_profile_ids         object
click                     int64
part_of_day               int64
weekday                   int64
weekend                   int64
os                       object
browser                  object
ad_slot_screen_share    float64
is_mobile_device           bool
dtype: object

In [6]:
df['click'] = df['click'].astype('bool')

In [7]:
pd.unique(df['domain']), len(pd.unique(df['domain']))

(array(['5eaa6ffce5e827b0907e99679585db6b',
        '72187db00c907f6304a240c763a6e70a',
        '39a2330a5cbc1a0ff7104e6aaddb1f68', ...,
        '72caec50a3242143fc49d4b23ef762d9',
        '42636e352d481b8fcd05c5e0b844ee70',
        'b0401d35bbcf270cc00fe757bbe49081'], dtype=object),
 19176)

In [8]:
df = df.drop("domain", axis=1)

In [9]:
pd.unique(df['os']), len(pd.unique(df['os']))

(array(['windows', 'other', 'mac', 'android', 'linux', 'ios'], dtype=object),
 6)

In [10]:
pd.unique(df['ad_slot_screen_share']), len(pd.unique(df['ad_slot_screen_share']))

(array([0.02676611, 0.07149067, 0.03812836, 0.06245425, 0.05957556,
        0.08967789, 0.0857888 , 0.08149936, 0.02859627, 0.09150805,
        0.08235725, 0.06519949, 0.02745242, 0.1875    , 0.06863104,
        0.15625   , 0.01338305, 0.196     , 0.2       , 0.18      ,
        0.08333333, 0.13020833, 0.01489389, 0.02573664, 0.1715776 ,
        0.1365    , 0.06      , 0.07806781, 0.1425    , 0.178125  ,
        0.0585    , 0.0625    , 0.15      , 0.10294656, 0.170625  ,
        0.03333333, 0.01525134, 0.05490483, 0.03545937, 0.18375   ,
        0.08407302, 0.07473158, 0.12      , 0.16333333, 0.05480951,
        0.225     , 0.11979167, 0.0775    ]),
 48)

In [11]:
df['ad_slot_screen_share'] = df['ad_slot_screen_share'].round(2)

In [12]:
pd.unique(df['user_profile_ids']), len(pd.unique(df['user_profile_ids']))

(array(['10684,14273,10052,10133', '10006',
        '10129,10024,10120,10145,10142,10063', ...,
        '10117,10083,10006,10024,10111,10127,13403',
        '10117,10083,13866,10006,10127,13403',
        '10059,10083,10006,10110,13776,10126,13403,10063,10116'],
       dtype=object),
 399768)

In [13]:
# df = df.drop("user_profile_ids", axis=1)

In [14]:
df.head()

bid_id  ...  is_mobile_device
0  b8c557a16cdd9cea7fa61df79bdb392d  ...             False
1  ce5a2b810ada0cad122508b4a9d1e2fd  ...             False
2  61fb95442aaa7cade3761b7f329a1e73  ...             False
3  7f9c3a72df3e4ded04870c08fcbcf72b  ...             False
4  de8192350f7e0f3223c43cf0c8cfb247  ...             False

[5 rows x 16 columns]

In [15]:
pd.unique(df['advertiser_id']), len(pd.unique(df['advertiser_id']))

(array([2259, 2821, 2997, 2261]), 4)

In [16]:
pd.unique(df['ad_slot_visibility']), len(pd.unique(df['ad_slot_visibility']))

(array(['OtherView', 'FirstView', 'Na', 'ThirdView', 'SecondView',
        'FourthView', 'FifthView'], dtype=object),
 7)

In [17]:
pd.unique(df['ad_slot_format']), len(pd.unique(df['ad_slot_format']))

(array(['Na'], dtype=object), 1)

In [18]:
pd.unique(df['creative_id']), len(pd.unique(df['creative_id']))

(array([ 7328,  7323,  7319,  7330,  7321,  7326,  7336,  7333,  7322,
         7317,  7335,  7331,  7314,  7315,  7320,  7316,  7318,  7325,
         7332,  7324, 10717, 10734, 10722, 10719, 10720, 10721, 10718,
        10723, 10733,  7327, 12987, 12620, 12626, 12625, 12616, 12633,
        12611, 12622, 12628, 12627, 12630, 12623, 12613, 12632, 12610,
        12618, 12621, 12629, 12615, 12631, 12619, 12624, 12612, 12614]),
 54)

In [19]:
df.to_csv("final_test_data_season_3.csv.zip", compression='zip')